version: '3'

services:
  task-management-api:
    container_name: trainee-app
    ports:
      - "8080:8080"
    build: ./
    restart: on-failure
    depends_on:
      - postgredb


  postgredb:
    image: 'postgres:12-alpine'
    container_name: postgredb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres